CREATE TABLE applications (
  application_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id INTEGER REFERENCES users(user_id) ON DELETE CASCADE NOT NULL,
  application_name TEXT NOT NULL,
  application_url TEXT NOT NULL,
  repository_prod TEXT NULL,
  repository_test TEXT NULL,
  database_prod TEXT NULL,
  database_test TEXT NULL
);